version: '3.9'

# See the usage instructions in the README.md

services:

    base-env:
        build:
            context: .
            dockerfile: dockerfiles/base.Dockerfile
            args:
                BASE_IMAGE: ubuntu:20.04
        image: ${NRP_DOCKER_REGISTRY}nrp-core/base-ubuntu20-env${NRP_CORE_TAG}
        command: bash


    nrp-vanilla-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            target: nrp-core-env
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/base-ubuntu20-env${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/vanilla.cmake
        image: ${NRP_DOCKER_REGISTRY}nrp-core/nrp-vanilla-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env


    nest-env:
        build:
            context: .
            dockerfile: dockerfiles/nest.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/base-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/nest-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env


    gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/gazebo.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/base-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/gazebo-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env


    gazebo-nest-env:
        build:
            context: .
            dockerfile: dockerfiles/gazebo.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/nest-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/gazebo-nest-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - nest-env


    nrp-gazebo-nest-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            target: nrp-core-env
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/gazebo-nest-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/nrp-gazebo-nest-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - gazebo-nest-env


    tvb-env:
        build:
            context: .
            dockerfile: dockerfiles/tvb.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/base-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/tvb-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env


    opensim-env:
        build:
            context: .
            dockerfile: dockerfiles/opensim.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/base-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/opensim-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env


    opensim-tvb-env:
        build:
            context: .
            dockerfile: dockerfiles/opensim.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/tvb-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/opensim-tvb-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - tvb-env


    base-nvidia-cuda-env:
        build:
            context: .
            dockerfile: dockerfiles/base.Dockerfile
            args:
                BASE_IMAGE: nvidia/cudagl:11.4.2-base-ubuntu20.04
        image: ${NRP_DOCKER_REGISTRY}nrp-core/base-nvidia-cuda-ubuntu20-env${NRP_CORE_TAG}
        command: bash


    nvidia-cuda-env:
        build:
            context: .
            dockerfile: dockerfiles/nvidia_cuda.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}nrp-core/base-nvidia-cuda-ubuntu20-env${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}nrp-core/nvidia-cuda-ubuntu20-env${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-nvidia-cuda-env
